### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.AdminExperience.Library#154]
@dnnsoftware/tag 

Here's what I propose to clean up branches and branch strategy here:

1. tag the `HEAD` of each release branch with a matching tag
1. merge release branches into `development` starting from the oldest
   - any conflicts should be resolved in favour of development
   - ideally, there shouldn't be any
1. delete release branches
1. delete `master` branch
1. rename `development -> master`
1. delete `development`

There are also some stale branches. Most probably should be removed. We can address them later

**Comment by bdukes** [comment]
Sounds good to me
